apiVersion: v1
kind: Service
metadata:
  name: microsservico-springboot-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8083
      nodePort: 32117 # Porta de acesso externo no Minikube
  selector:
    app: microsservico-springboot
